version: '3.9'

services:
  redis-node-1:
    image: redis:7.2-alpine
    container_name: redis-node-1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-node-1.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7001:7001
      - 17001:17001

  redis-node-2:
    image: redis:7.2-alpine
    container_name: redis-node-2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-node-2.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7002:7002
      - 17002:17002

  redis-node-3:
    image: redis:7.2-alpine
    container_name: redis-node-3
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-node-3.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7003:7003
      - 17003:17003

  redis-node-4:
    image: redis:7.2-alpine
    container_name: redis-node-4
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-node-4.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7004:7004
      - 17004:17004

  redis-node-5:
    image: redis:7.2-alpine
    container_name: redis-node-5
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-node-5.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7005:7005
      - 17005:17005

  redis-node-6:
    image: redis:7.2-alpine
    container_name: redis-node-6
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-node-6.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 7006:7006
      - 17006:17006

